"""Explicit mirror of top-level ``daft`` public API.

Generated by ``scripts/regenerate_api_mirror.py``. Do not edit by hand.
"""
from __future__ import annotations

from typing import Any

import daft
import daft.functions as _daft_functions

from unite_stream.dataframe import UniteStreamDataFrame
from unite_stream.udf import cls, func, method, metrics, udf
from unite_stream.wrap_util import wrap_result


class UniteStreamNamespace:
    """One explicit static method / class attribute per public ``daft`` API."""

    @staticmethod
    def from_arrow(*args: Any, **kwargs: Any) -> UniteStreamDataFrame:
        return wrap_result(daft.from_arrow(*args, **kwargs))

    @staticmethod
    def from_files(*args: Any, **kwargs: Any) -> UniteStreamDataFrame:
        return wrap_result(daft.from_files(*args, **kwargs))

    @staticmethod
    def from_glob_path(*args: Any, **kwargs: Any) -> UniteStreamDataFrame:
        return wrap_result(daft.from_glob_path(*args, **kwargs))

    @staticmethod
    def from_pandas(*args: Any, **kwargs: Any) -> UniteStreamDataFrame:
        return wrap_result(daft.from_pandas(*args, **kwargs))

    @staticmethod
    def from_pydict(*args: Any, **kwargs: Any) -> UniteStreamDataFrame:
        return wrap_result(daft.from_pydict(*args, **kwargs))

    @staticmethod
    def from_pylist(*args: Any, **kwargs: Any) -> UniteStreamDataFrame:
        return wrap_result(daft.from_pylist(*args, **kwargs))

    @staticmethod
    def range(*args: Any, **kwargs: Any) -> UniteStreamDataFrame:
        return wrap_result(daft.range(*args, **kwargs))

    @staticmethod
    def read_csv(*args: Any, **kwargs: Any) -> UniteStreamDataFrame:
        return wrap_result(daft.read_csv(*args, **kwargs))

    @staticmethod
    def read_deltalake(*args: Any, **kwargs: Any) -> UniteStreamDataFrame:
        return wrap_result(daft.read_deltalake(*args, **kwargs))

    @staticmethod
    def read_hudi(*args: Any, **kwargs: Any) -> UniteStreamDataFrame:
        return wrap_result(daft.read_hudi(*args, **kwargs))

    @staticmethod
    def read_huggingface(*args: Any, **kwargs: Any) -> UniteStreamDataFrame:
        return wrap_result(daft.read_huggingface(*args, **kwargs))

    @staticmethod
    def read_iceberg(*args: Any, **kwargs: Any) -> UniteStreamDataFrame:
        return wrap_result(daft.read_iceberg(*args, **kwargs))

    @staticmethod
    def read_json(*args: Any, **kwargs: Any) -> UniteStreamDataFrame:
        return wrap_result(daft.read_json(*args, **kwargs))

    @staticmethod
    def read_kafka(*args: Any, **kwargs: Any) -> UniteStreamDataFrame:
        return wrap_result(daft.read_kafka(*args, **kwargs))

    @staticmethod
    def read_lance(*args: Any, **kwargs: Any) -> UniteStreamDataFrame:
        return wrap_result(daft.read_lance(*args, **kwargs))

    @staticmethod
    def read_mcap(*args: Any, **kwargs: Any) -> UniteStreamDataFrame:
        return wrap_result(daft.read_mcap(*args, **kwargs))

    @staticmethod
    def read_paimon(*args: Any, **kwargs: Any) -> UniteStreamDataFrame:
        return wrap_result(daft.read_paimon(*args, **kwargs))

    @staticmethod
    def read_parquet(*args: Any, **kwargs: Any) -> UniteStreamDataFrame:
        return wrap_result(daft.read_parquet(*args, **kwargs))

    @staticmethod
    def read_table(*args: Any, **kwargs: Any) -> UniteStreamDataFrame:
        return wrap_result(daft.read_table(*args, **kwargs))

    @staticmethod
    def read_text(*args: Any, **kwargs: Any) -> UniteStreamDataFrame:
        return wrap_result(daft.read_text(*args, **kwargs))

    @staticmethod
    def read_video_frames(*args: Any, **kwargs: Any) -> UniteStreamDataFrame:
        return wrap_result(daft.read_video_frames(*args, **kwargs))

    @staticmethod
    def read_warc(*args: Any, **kwargs: Any) -> UniteStreamDataFrame:
        return wrap_result(daft.read_warc(*args, **kwargs))

    @staticmethod
    def col(*args: Any, **kwargs: Any) -> Any:
        return daft.col(*args, **kwargs)

    @staticmethod
    def element(*args: Any, **kwargs: Any) -> Any:
        return daft.element(*args, **kwargs)

    @staticmethod
    def interval(*args: Any, **kwargs: Any) -> Any:
        return daft.interval(*args, **kwargs)

    @staticmethod
    def lit(*args: Any, **kwargs: Any) -> Any:
        return daft.lit(*args, **kwargs)

    @staticmethod
    def cls(*args: Any, **kwargs: Any) -> Any:
        return cls(*args, **kwargs)

    @staticmethod
    def func(*args: Any, **kwargs: Any) -> Any:
        return func(*args, **kwargs)

    @staticmethod
    def method(*args: Any, **kwargs: Any) -> Any:
        return method(*args, **kwargs)

    @staticmethod
    def metrics(*args: Any, **kwargs: Any) -> Any:
        return metrics(*args, **kwargs)

    @staticmethod
    def udf(*args: Any, **kwargs: Any) -> Any:
        return udf(*args, **kwargs)

    @staticmethod
    def attach(*args: Any, **kwargs: Any) -> Any:
        return daft.attach(*args, **kwargs)

    @staticmethod
    def attach_catalog(*args: Any, **kwargs: Any) -> Any:
        return daft.attach_catalog(*args, **kwargs)

    @staticmethod
    def attach_function(*args: Any, **kwargs: Any) -> Any:
        return daft.attach_function(*args, **kwargs)

    @staticmethod
    def attach_provider(*args: Any, **kwargs: Any) -> Any:
        return daft.attach_provider(*args, **kwargs)

    @staticmethod
    def attach_subscriber(*args: Any, **kwargs: Any) -> Any:
        return daft.attach_subscriber(*args, **kwargs)

    @staticmethod
    def attach_table(*args: Any, **kwargs: Any) -> Any:
        return daft.attach_table(*args, **kwargs)

    @staticmethod
    def create_namespace(*args: Any, **kwargs: Any) -> Any:
        return daft.create_namespace(*args, **kwargs)

    @staticmethod
    def create_namespace_if_not_exists(*args: Any, **kwargs: Any) -> Any:
        return daft.create_namespace_if_not_exists(*args, **kwargs)

    @staticmethod
    def create_table(*args: Any, **kwargs: Any) -> Any:
        return daft.create_table(*args, **kwargs)

    @staticmethod
    def create_table_if_not_exists(*args: Any, **kwargs: Any) -> Any:
        return daft.create_table_if_not_exists(*args, **kwargs)

    @staticmethod
    def create_temp_table(*args: Any, **kwargs: Any) -> Any:
        return daft.create_temp_table(*args, **kwargs)

    @staticmethod
    def current_catalog(*args: Any, **kwargs: Any) -> Any:
        return daft.current_catalog(*args, **kwargs)

    @staticmethod
    def current_model(*args: Any, **kwargs: Any) -> Any:
        return daft.current_model(*args, **kwargs)

    @staticmethod
    def current_namespace(*args: Any, **kwargs: Any) -> Any:
        return daft.current_namespace(*args, **kwargs)

    @staticmethod
    def current_provider(*args: Any, **kwargs: Any) -> Any:
        return daft.current_provider(*args, **kwargs)

    @staticmethod
    def current_session(*args: Any, **kwargs: Any) -> Any:
        return daft.current_session(*args, **kwargs)

    @staticmethod
    def detach_catalog(*args: Any, **kwargs: Any) -> Any:
        return daft.detach_catalog(*args, **kwargs)

    @staticmethod
    def detach_function(*args: Any, **kwargs: Any) -> Any:
        return daft.detach_function(*args, **kwargs)

    @staticmethod
    def detach_provider(*args: Any, **kwargs: Any) -> Any:
        return daft.detach_provider(*args, **kwargs)

    @staticmethod
    def detach_subscriber(*args: Any, **kwargs: Any) -> Any:
        return daft.detach_subscriber(*args, **kwargs)

    @staticmethod
    def detach_table(*args: Any, **kwargs: Any) -> Any:
        return daft.detach_table(*args, **kwargs)

    @staticmethod
    def drop_namespace(*args: Any, **kwargs: Any) -> Any:
        return daft.drop_namespace(*args, **kwargs)

    @staticmethod
    def drop_table(*args: Any, **kwargs: Any) -> Any:
        return daft.drop_table(*args, **kwargs)

    @staticmethod
    def execution_config_ctx(*args: Any, **kwargs: Any) -> Any:
        return daft.execution_config_ctx(*args, **kwargs)

    @staticmethod
    def get_build_type(*args: Any, **kwargs: Any) -> Any:
        return daft.get_build_type(*args, **kwargs)

    @staticmethod
    def get_catalog(*args: Any, **kwargs: Any) -> Any:
        return daft.get_catalog(*args, **kwargs)

    @staticmethod
    def get_context(*args: Any, **kwargs: Any) -> Any:
        return daft.get_context(*args, **kwargs)

    @staticmethod
    def get_function(*args: Any, **kwargs: Any) -> Any:
        return daft.get_function(*args, **kwargs)

    @staticmethod
    def get_provider(*args: Any, **kwargs: Any) -> Any:
        return daft.get_provider(*args, **kwargs)

    @staticmethod
    def get_table(*args: Any, **kwargs: Any) -> Any:
        return daft.get_table(*args, **kwargs)

    @staticmethod
    def get_version(*args: Any, **kwargs: Any) -> Any:
        return daft.get_version(*args, **kwargs)

    @staticmethod
    def has_catalog(*args: Any, **kwargs: Any) -> Any:
        return daft.has_catalog(*args, **kwargs)

    @staticmethod
    def has_namespace(*args: Any, **kwargs: Any) -> Any:
        return daft.has_namespace(*args, **kwargs)

    @staticmethod
    def has_provider(*args: Any, **kwargs: Any) -> Any:
        return daft.has_provider(*args, **kwargs)

    @staticmethod
    def has_table(*args: Any, **kwargs: Any) -> Any:
        return daft.has_table(*args, **kwargs)

    @staticmethod
    def list_catalogs(*args: Any, **kwargs: Any) -> Any:
        return daft.list_catalogs(*args, **kwargs)

    @staticmethod
    def list_tables(*args: Any, **kwargs: Any) -> Any:
        return daft.list_tables(*args, **kwargs)

    @staticmethod
    def load_extension(*args: Any, **kwargs: Any) -> Any:
        return daft.load_extension(*args, **kwargs)

    @staticmethod
    def planning_config_ctx(*args: Any, **kwargs: Any) -> Any:
        return daft.planning_config_ctx(*args, **kwargs)

    @staticmethod
    def refresh_logger(*args: Any, **kwargs: Any) -> Any:
        return daft.refresh_logger(*args, **kwargs)

    @staticmethod
    def register_viz_hook(*args: Any, **kwargs: Any) -> Any:
        return daft.register_viz_hook(*args, **kwargs)

    @staticmethod
    def session(*args: Any, **kwargs: Any) -> Any:
        return daft.session(*args, **kwargs)

    @staticmethod
    def set_catalog(*args: Any, **kwargs: Any) -> Any:
        return daft.set_catalog(*args, **kwargs)

    @staticmethod
    def set_execution_config(*args: Any, **kwargs: Any) -> Any:
        return daft.set_execution_config(*args, **kwargs)

    @staticmethod
    def set_model(*args: Any, **kwargs: Any) -> Any:
        return daft.set_model(*args, **kwargs)

    @staticmethod
    def set_namespace(*args: Any, **kwargs: Any) -> Any:
        return daft.set_namespace(*args, **kwargs)

    @staticmethod
    def set_planning_config(*args: Any, **kwargs: Any) -> Any:
        return daft.set_planning_config(*args, **kwargs)

    @staticmethod
    def set_provider(*args: Any, **kwargs: Any) -> Any:
        return daft.set_provider(*args, **kwargs)

    @staticmethod
    def set_session(*args: Any, **kwargs: Any) -> Any:
        return daft.set_session(*args, **kwargs)

    @staticmethod
    def with_subscriber(*args: Any, **kwargs: Any) -> Any:
        return daft.with_subscriber(*args, **kwargs)



UniteStreamNamespace.AudioFile = daft.AudioFile
UniteStreamNamespace.Catalog = daft.Catalog
UniteStreamNamespace.DataFrame = daft.DataFrame
UniteStreamNamespace.DataType = daft.DataType
UniteStreamNamespace.Expression = daft.Expression
UniteStreamNamespace.File = daft.File
UniteStreamNamespace.IOConfig = daft.IOConfig
UniteStreamNamespace.Identifier = daft.Identifier
UniteStreamNamespace.ImageFormat = daft.ImageFormat
UniteStreamNamespace.ImageMode = daft.ImageMode
UniteStreamNamespace.ImageProperty = daft.ImageProperty
UniteStreamNamespace.MediaType = daft.MediaType
UniteStreamNamespace.ResourceRequest = daft.ResourceRequest
UniteStreamNamespace.Schema = daft.Schema
UniteStreamNamespace.Series = daft.Series
UniteStreamNamespace.Session = daft.Session
UniteStreamNamespace.Table = daft.Table
UniteStreamNamespace.TimeUnit = daft.TimeUnit
UniteStreamNamespace.VideoFile = daft.VideoFile
UniteStreamNamespace.Window = daft.Window

UniteStreamNamespace.functions = _daft_functions

UniteStream = UniteStreamNamespace()
UniteStreamModule = UniteStreamNamespace
