# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: daft/v1/worker.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'daft/v1/worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from daft.runtime.daft_proto.daft_runtime_proto.v1 import udf_pb2 as daft_dot_v1_dot_udf__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64\x61\x66t/v1/worker.proto\x12\x07\x64\x61\x66t.v1\x1a\x11\x64\x61\x66t/v1/udf.proto\"o\n\x0eWorkerEnvelope\x12%\n\x05hello\x18\x01 \x01(\x0b\x32\x14.daft.v1.WorkerHelloH\x00\x12+\n\x08response\x18\x02 \x01(\x0b\x32\x17.daft.v1.WorkerResponseH\x00\x42\t\n\x07payload\"H\n\x0bWorkerHello\x12\x0b\n\x03pid\x18\x01 \x01(\x03\x12\x16\n\x0epython_version\x18\x02 \x01(\t\x12\x14\n\x0c\x64\x61\x66t_version\x18\x03 \x01(\t\"\xa4\x01\n\rWorkerRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\x04\x12.\n\x07\x65xecute\x18\x02 \x01(\x0b\x32\x1b.daft.v1.ExecutePlanRequestH\x00\x12\x1d\n\x04ping\x18\x03 \x01(\x0b\x32\r.daft.v1.PingH\x00\x12%\n\x08shutdown\x18\x04 \x01(\x0b\x32\x11.daft.v1.ShutdownH\x00\x42\t\n\x07\x63ommand\"\xfb\x01\n\x12\x45xecutePlanRequest\x12\x14\n\x0clogical_plan\x18\x01 \x01(\x0c\x12\x46\n\x0epartition_sets\x18\x02 \x03(\x0b\x32..daft.v1.ExecutePlanRequest.PartitionSetsEntry\x12\x13\n\x0b\x65xtra_paths\x18\x03 \x03(\t\x12$\n\x04udfs\x18\x04 \x03(\x0b\x32\x16.daft.v1.UdfDescriptor\x12\x16\n\x0epython_version\x18\x05 \x01(\t\x1a\x34\n\x12PartitionSetsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"\x06\n\x04Ping\"\n\n\x08Shutdown\"\xa8\x01\n\x0eWorkerResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\x04\x12/\n\x07\x65xecute\x18\x02 \x01(\x0b\x32\x1c.daft.v1.ExecutePlanResponseH\x00\x12\x1d\n\x04pong\x18\x03 \x01(\x0b\x32\r.daft.v1.PongH\x00\x12(\n\x08shutdown\x18\x04 \x01(\x0b\x32\x14.daft.v1.ShutdownAckH\x00\x42\x08\n\x06result\"4\n\x13\x45xecutePlanResponse\x12\x0e\n\x06result\x18\x01 \x01(\x0c\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x06\n\x04Pong\"\r\n\x0bShutdownAckB,\n\x14\x63om.daft.protocol.v1B\x0bWorkerProtoZ\x07\x64\x61\x66t/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'daft.v1.worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.daft.protocol.v1B\013WorkerProtoZ\007daft/v1'
  _globals['_EXECUTEPLANREQUEST_PARTITIONSETSENTRY']._loaded_options = None
  _globals['_EXECUTEPLANREQUEST_PARTITIONSETSENTRY']._serialized_options = b'8\001'
  _globals['_WORKERENVELOPE']._serialized_start=52
  _globals['_WORKERENVELOPE']._serialized_end=163
  _globals['_WORKERHELLO']._serialized_start=165
  _globals['_WORKERHELLO']._serialized_end=237
  _globals['_WORKERREQUEST']._serialized_start=240
  _globals['_WORKERREQUEST']._serialized_end=404
  _globals['_EXECUTEPLANREQUEST']._serialized_start=407
  _globals['_EXECUTEPLANREQUEST']._serialized_end=658
  _globals['_EXECUTEPLANREQUEST_PARTITIONSETSENTRY']._serialized_start=606
  _globals['_EXECUTEPLANREQUEST_PARTITIONSETSENTRY']._serialized_end=658
  _globals['_PING']._serialized_start=660
  _globals['_PING']._serialized_end=666
  _globals['_SHUTDOWN']._serialized_start=668
  _globals['_SHUTDOWN']._serialized_end=678
  _globals['_WORKERRESPONSE']._serialized_start=681
  _globals['_WORKERRESPONSE']._serialized_end=849
  _globals['_EXECUTEPLANRESPONSE']._serialized_start=851
  _globals['_EXECUTEPLANRESPONSE']._serialized_end=903
  _globals['_PONG']._serialized_start=905
  _globals['_PONG']._serialized_end=911
  _globals['_SHUTDOWNACK']._serialized_start=913
  _globals['_SHUTDOWNACK']._serialized_end=926
# @@protoc_insertion_point(module_scope)
